train:
  _target_: src.datasets.example.ExampleDataset
  root: "data/ASVspoof2019/LA"
  split: "train"
  sample_rate: 16000
  n_fft: 512
  win_length: 400
  hop_length: 160
  limit: null
  shuffle_index: true
  instance_transforms: ${transforms.instance_transforms.train}

val:
  _target_: src.datasets.example.ExampleDataset
  root: "data/ASVspoof2019/LA"
  split: "dev"
  sample_rate: 16000
  n_fft: 512
  win_length: 400
  hop_length: 160
  limit: null
  shuffle_index: false
  instance_transforms: ${transforms.instance_transforms.inference}

test:
  _target_: src.datasets.example.ExampleDataset
  root: "data/ASVspoof2019/LA"
  split: "dev"
  sample_rate: 16000
  n_fft: 512
  win_length: 400
  hop_length: 160
  limit: null
  shuffle_index: false
  instance_transforms: ${transforms.instance_transforms.inference}